/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_fletchmckee_ktjni_samples_simple_Parent__Child */

#ifndef _Included_io_github_fletchmckee_ktjni_samples_simple_Parent__Child
#define _Included_io_github_fletchmckee_ktjni_samples_simple_Parent__Child
#ifdef __cplusplus
extern "C" {
#endif

#undef io_github_fletchmckee_ktjni_samples_simple_Parent__Child_VERSION
#define io_github_fletchmckee_ktjni_samples_simple_Parent__Child_VERSION 1L

/*
 * Class:     io_github_fletchmckee_ktjni_samples_simple_Parent__Child
 * Method:    childJniMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_fletchmckee_ktjni_samples_simple_Parent_00024Child_childJniMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
