/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_fletchmckee_ktjni_samples_simple_NativeLib */

#ifndef _Included_io_github_fletchmckee_ktjni_samples_simple_NativeLib
#define _Included_io_github_fletchmckee_ktjni_samples_simple_NativeLib
#ifdef __cplusplus
extern "C" {
#endif

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_VERSION
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_VERSION 42L

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_PI
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_PI 3.14159

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_ENABLED
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_ENABLED 1L

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_RATIO
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_RATIO 2.5f

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_MAX_VALUE
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_MAX_VALUE 9223372036854775807LL

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_NAME
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_NAME "NativeLib"

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_X_CHAR
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_X_CHAR 88L

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_MIN_BYTE
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_MIN_BYTE -128L

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_MAX_SHORT
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_MAX_SHORT 32767L

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_POS_INFINITY
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_POS_INFINITY Inff

#undef io_github_fletchmckee_ktjni_samples_simple_NativeLib_NEG_INFINITY
#define io_github_fletchmckee_ktjni_samples_simple_NativeLib_NEG_INFINITY -InfD

/*
 * Class:     io_github_fletchmckee_ktjni_samples_simple_NativeLib
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_fletchmckee_ktjni_samples_simple_NativeLib_stringFromJni
  (JNIEnv *, jobject);

/*
 * Class:     io_github_fletchmckee_ktjni_samples_simple_NativeLib
 * Method:    longFromJni
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_fletchmckee_ktjni_samples_simple_NativeLib_longFromJni__
  (JNIEnv *, jobject);

/*
 * Class:     io_github_fletchmckee_ktjni_samples_simple_NativeLib
 * Method:    longFromJni
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_github_fletchmckee_ktjni_samples_simple_NativeLib_longFromJni__J
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
