/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_fletchmckee_ktjni_samples_simple_Extension__SubExtension */

#ifndef _Included_io_github_fletchmckee_ktjni_samples_simple_Extension__SubExtension
#define _Included_io_github_fletchmckee_ktjni_samples_simple_Extension__SubExtension
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     io_github_fletchmckee_ktjni_samples_simple_Extension__SubExtension
 * Method:    anotherTest
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_github_fletchmckee_ktjni_samples_simple_Extension_00024SubExtension_anotherTest
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
