/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_fletchmckee_ktjni_samples_simple_Parent */

#ifndef _Included_io_github_fletchmckee_ktjni_samples_simple_Parent
#define _Included_io_github_fletchmckee_ktjni_samples_simple_Parent
#ifdef __cplusplus
extern "C" {
#endif

#undef io_github_fletchmckee_ktjni_samples_simple_Parent_VERSION
#define io_github_fletchmckee_ktjni_samples_simple_Parent_VERSION 1L

/*
 * Class:     io_github_fletchmckee_ktjni_samples_simple_Parent
 * Method:    parentJniMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_fletchmckee_ktjni_samples_simple_Parent_parentJniMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
