/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_fletchmckee_ktjni_samples_simple_Extension */

#ifndef _Included_io_github_fletchmckee_ktjni_samples_simple_Extension
#define _Included_io_github_fletchmckee_ktjni_samples_simple_Extension
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     io_github_fletchmckee_ktjni_samples_simple_Extension
 * Method:    nativeExtension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_fletchmckee_ktjni_samples_simple_Extension_nativeExtension__
  (JNIEnv *, jobject);

/*
 * Class:     io_github_fletchmckee_ktjni_samples_simple_Extension
 * Method:    nativeExtension
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_fletchmckee_ktjni_samples_simple_Extension_nativeExtension___3F_3F
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     io_github_fletchmckee_ktjni_samples_simple_Extension
 * Method:    nativeExtension
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_fletchmckee_ktjni_samples_simple_Extension_nativeExtension__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_fletchmckee_ktjni_samples_simple_Extension
 * Method:    nativeExtensionV2
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_fletchmckee_ktjni_samples_simple_Extension_nativeExtensionV2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
